credentials:
  usernames:
    test_user:
      email: pchichghare@synoptek.com
      name: Test User
      password: $2b$12$mLIRinWCi1Sb2gKuudzaL.K4vyk3mV9uhpsWBVxudUAiWmdRPT.Iy
cookie:
  expiry_days: 30
  key: random_signature_key # Must be string
  name: random_cookie_name